### PR TITLE
Add a date utility

### PR DESCRIPTION
**Pull request by lifetimelearn3r**
# Changes proposed in this pull request:
- Added Date utility to check if a date is between 2 given dates
- Added unit tests

### CODE REVIEW

**Review by zaimramlan — CHANGES_REQUESTED** [review]
Thanks for contributing! Can you please add some notes on how to use the utility in the `README.md` under `ProductivityKit/ProductivityKit/Date`? 

That will help future developers know how to use them :)

**Comment by boot-ims** [comment]
Sure thing. Thanks for taking the time to review!

**Comment by boot-ims** [comment]
Aight mate, changes are pushed.

**Review by zaimramlan — APPROVED** [review]
Cheers for helping out 👍

**Pull request merged**
